pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Hyprland

QtObject {
    id: root

    // ---- static data (generated by tools/) ----
    property var rooms: ({})          // ws -> {id, plates, ambient}
    property var manifest: ({})       // skybox + sprites manifest
    property var dialogue: ({})       // room -> [ {speaker,text,sprite,sfx,...} ]

    // ---- live state ----
    property int currentWs: 1
    readonly property var room: rooms[String(currentWs)] ?? null
    readonly property string roomId: room?.id ?? "hub"

    property int skyboxIndex: 0
    property int plateIndex: 0
    property bool showSkybox: false   // intro-style skybox art; off by default
    property bool voiceMuted: false
    property bool speaking: false   // dialogue typewriter active -> sprite mouth

    // sprite reseed trigger (bump to randomize pose/emotion/variant)
    property int spriteEpoch: 0
    property string spritePose: "arms_down"
    property string spriteEmotion: "neutral"
    property int spriteVariant: 1

    signal didChangeRoom(string roomId)
    signal dialogueRequested(var line)
    signal skyboxChanged(int index)

    // ----------------------------------------------------------------
    function loadJson(path, cb) {
        const xhr = new XMLHttpRequest();
        xhr.open("GET", Qt.resolvedUrl(path));
        xhr.onload = () => {
            try {
                cb(JSON.parse(xhr.responseText));
            } catch (e) {
                console.warn(`[hyprmilk] failed to parse ${path}: ${e}`);
            }
        };
        xhr.onerror = () => console.warn(`[hyprmilk] failed to load ${path}`);
        xhr.send();
    }

    function reseedSprite(pose, emotion) {
        const sprites = manifest.sprites;
        const poseKey = pose && sprites[pose] ? pose
            : Object.keys(sprites)[Math.floor(Math.random() * Object.keys(sprites).length)];
        const emos = Object.keys(sprites[poseKey]);
        const emoKey = emotion && sprites[poseKey][emotion] ? emotion
            : emos[Math.floor(Math.random() * emos.length)];
        const bodies = sprites[poseKey][emoKey].bodies;
        spritePose = poseKey;
        spriteEmotion = emoKey;
        spriteVariant = bodies[Math.floor(Math.random() * bodies.length)];
        spriteEpoch++;
    }

    function rerollSkybox() {
        const range = manifest?.skybox?.default_range ?? [];
        if (!range.length)
            return;
        let next;
        do {
            next = range[Math.floor(Math.random() * range.length)];
        } while (range.length > 1 && next === skyboxIndex);
        skyboxIndex = next;
        skyboxChanged(next);
    }

    // launcher action: show the skybox layer and pick a new frame
    function toggleSkybox() {
        showSkybox = true;
        rerollSkybox();
    }

    function nextPlate() {
        const plates = room?.plates ?? [];
        if (plates.length < 2)
            return;
        plateIndex = (plateIndex + 1) % plates.length;
    }

    function randomPlate() {
        const plates = room?.plates ?? [];
        if (!plates.length)
            return;
        plateIndex = Math.floor(Math.random() * plates.length);
    }

    function say(line) {
        dialogueRequested(line);
    }

    function sayRandom() {
        const lines = dialogue[roomId];
        if (!lines?.length)
            return;
        const line = lines[Math.floor(Math.random() * lines.length)];
        say(line);
    }

    function toggleVoice() {
        voiceMuted = !voiceMuted;
        const p = Quickshell.env("XDG_STATE_HOME") + "/hyprmilk";
        Quickshell.execDetached(["sh", "-c",
            `mkdir -p '${p}' && echo ${voiceMuted ? 1 : 0} > '${p}/voice`]);
    }

    onCurrentWsChanged: {
        randomPlate();
        reseedSprite();
        didChangeRoom(roomId);
        sayRandom();
    }

    // ----------------------------------------------------------------

    Component.onCompleted: {
        loadJson("data/rooms.json", v => root.rooms = v);
        loadJson("data/manifest.json", v => {
            root.manifest = v;
            root.rerollSkybox();
            root.reseedSprite();
        });
        loadJson("data/dialogue.json", v => root.dialogue = v);

        const m = Hyprland.focusedMonitor;
        if (m?.activeWorkspace)
            currentWs = m.activeWorkspace.id;

        // restore voice mute state
        const xhr = new XMLHttpRequest();
        xhr.open("GET", Qt.resolvedUrl(
            (Quickshell.env("XDG_STATE_HOME") || Quickshell.env("HOME") + "/.local/state")
            + "/hyprmilk/voice"));
        xhr.onload = () => root.voiceMuted = xhr.responseText.trim() === "1";
        try { xhr.send(); } catch (e) {}
    }
}
